spring:
  application:
    name: client-shell
  shell:
    interactive:
      enabled: true
    command:
      help:
        enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRE_URL:jdbc:postgresql://localhost:5432/shopdb}
    username: ${POSTGRE_USERNAME:postgres}
    password: ${POSTGRE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 9095

app:
  kafkaA:
    bootstrap: ${BOOTSTRAP_SERVERS_CLUSTER_A:localhost:9094,localhost:9095,localhost:9096}
    jaas-config: org.apache.kafka.common.security.plain.PlainLoginModule required username="client" password="changeit";
    truststore-location: ${TRUSTSTORE_LOCATION:certs/truststore.jks}
    truststore-password: ${TRUSTSTORE_PASSWORD:changeit}
  kafkaB:
    bootstrap: ${BOOTSTRAP_SERVERS_CLUSTER_B:localhost:9097,localhost:9098,localhost:9099}
    jaas-config: org.apache.kafka.common.security.plain.PlainLoginModule required username="client" password="changeit";
    truststore-location: ${TRUSTSTORE_LOCATION:certs/truststore.jks}
    truststore-password: ${TRUSTSTORE_PASSWORD:changeit}

topics:
  requests: "client.requests"
  recommendations: "client.recommendations"
  forbidden: "forbidden.skus"